name: Jvm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BDB_CLIENT_TOKEN: ${{ secrets.BDB_CLIENT_TOKEN }}

jobs:
  gradle:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: 'recursive'
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Build files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: jvmTest
      - name: Archive Reports
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: reports
          path: build/reports/
