name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BDB_CLIENT_TOKEN: ${{ secrets.BDB_CLIENT_TOKEN }}

jobs:
  gradle:
    strategy:
      matrix:
        os: [macos-latest] #windows-latest, ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: 'recursive'
      - run: sudo apt-get update --fix-missing && sudo apt-get install libcurl4-openssl-dev
        name: Install libcurl-dev
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Build files
        uses: actions/cache@v2
        if: ${{ !startsWith(matrix.os, 'windows') }}
        with:
          path: |
            ~/.konan
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}
#      - uses: eskatos/gradle-command-action@v1
#        name: Test Windows Target
#        if: ${{ startsWith(matrix.os, 'windows') }}
#        with:
#          arguments: win64Test
      - uses: eskatos/gradle-command-action@v1
        name: Test Apple and Jvm Targets
        if: ${{ startsWith(matrix.os, 'macos') }}
        with:
          arguments: walletkit:macosTest walletkit:iosX64Test :walletkit:jvmTest #tvosTest watchosX86Test
      - name: Test Android targets
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew connectedCheck
#      - uses: eskatos/gradle-command-action@v1
#        name: Test Linux Target
#        if: ${{ startsWith(matrix.os, 'ubuntu') }}
#        with:
#          arguments: linuxX64Test
      - name: Archive Reports
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: reports
          path: build/reports/
